# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fec973d50145b5a0faf82588983c3b4a50a55ac1df32f5d181e6c1a4fa09468948005c328343b00df843175d0097f8c13049ee42bffbd11c0726b150678ad2

test:
  secret_key_base: 66f1366653d62edc7f373a8766d94d93f1112ead48328e6b9f038c8a1822ccadc63b8e132027b3c42ca43e1ec7061f75f37a4eade41a91172018c993d810d323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
